CREATE TABLE "users" (
    "user_id" SERIAL PRIMARY KEY,
    "user_name" VARCHAR
);
CREATE TABLE "users2" (
    "user_id" INTEGER GENERATED BY DEFAULT as IDENTITY PRIMARY KEY,
    "user_name" VARCHAR
);
CREATE TABLE "users3" (
    "user_id" INTEGER GENERATED ALWAYS as IDENTITY PRIMARY KEY,
    "user_name" VARCHAR
);
CREATE TABLE "users4" (
    "user_id" INTEGER GENERATED ALWAYS as IDENTITY (START WITH 100 INCREMENT BY 2) PRIMARY KEY,
    "user_name" VARCHAR
);
CREATE TABLE usersDual (
    id1 INTEGER,
    id2 INTEGER,
    PRIMARY KEY (id1, id2)
);
SELECT gen_random_uuid(),
    uuid_generate_v4();
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
DROP EXTENSION "uuid-ossp";
CREATE TABLE "users5" (
    "user_id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    "username" VARCHAR
);
CREATE SEQUENCE user_sequence;
DROP SEQUENCE user_sequence;
SELECT nextval('user_sequence'),
    currval('user_sequence');
CREATE TABLE "users6" (
    "user_id" BIGINT PRIMARY KEY DEFAULT nextval('user_sequence'),
    "user_name" VARCHAR
);